"""empty message

Revision ID: 1718a9dd1a2d
Revises: c7c6308fc04a
Create Date: 2021-03-23 23:09:30.466633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1718a9dd1a2d'
down_revision = 'c7c6308fc04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perguntas', sa.Column('dificuldade', sa.Integer(), nullable=True))
    op.alter_column('respostas', 'correta',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('respostas', 'correta',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('perguntas', 'dificuldade')
    # ### end Alembic commands ###
