"""Campo classe para a dificuldade

Revision ID: b825222a9748
Revises: 1718a9dd1a2d
Create Date: 2021-04-03 21:02:28.431624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b825222a9748'
down_revision = '1718a9dd1a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perguntas', sa.Column('classe', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perguntas', 'classe')
    # ### end Alembic commands ###
