"""empty message

Revision ID: c7c6308fc04a
Revises: 
Create Date: 2021-03-23 00:25:25.442220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c6308fc04a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=140), nullable=True),
    sa.Column('pergunta_id', sa.Integer(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    op.drop_table('perguntas')
    # ### end Alembic commands ###
